# Data paths
data:
  base_dir: "./data/raw"

  # Input data
  input:
    images_dir: "final_output"
    image_pattern: "sample_{:05d}.tif"
    final_results_csv: "final_output/final_results.csv"
    tau_results_csv: "final_output/taufactor_results.csv"
    parquet_dir: "final_pybamm_output"
    parquet_pattern: "sample_{:05d}.parquet"

  # Output data
  output:
    intermediate_dir: "./data/intermediate"
    optimized_dir: "./data/optimized"
    train_dir: "train"
    val_dir: "val"
    test_dir: "test"
    stats_file: "normalization_stats.json"
